spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: "jdbc:postgresql://localhost:5432/orchestrator"


app:
  aws:
    region-name: "us-east-1"
    s3-endpoint: "http://localhost:9000"
