spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: "jdbc:postgresql://localhost:5432/orchestrator"

  rabbitmq:
    host: localhost
    port: 5672
    password: ${RABBIT_PASSWORD}
    username: ${RABBIT_USER}

app:
  aws:
    region-name: "us-east-1"
    s3-endpoint: "http://localhost:9000"
